blog/urls.py
from django.urls import path

from . import views


urlpatterns = [
    # path('get_author', views.get_author),
    path('register', views.register, name = "register"),
    # path("submitaction", views.submitaction, name = "submitaction")
]
app_name = "blog"

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include("blog.urls"))
]

blog/models.py
from django.db import models

from .choice import AuthorStatus
from django.db.models import QuerySet

class AuthorQuerySet(QuerySet):
    def active(self):
        return self.filter(status=AuthorStatus.ACTIVE)


# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=255)
    objects = AuthorQuerySet.as_manager()
    status = models.CharField(choices=AuthorStatus,
                              validators=[AuthorStatus.validator],
                              null=True,
                              max_length=64)
    address = models.TextField()
    email = models.EmailField()
    dob = models.DateField()
    country = models.CharField(max_length=255)



    def __str__(self):
        return f"{self.id}_{self.name}"


class Student(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    resume = models.FileField(upload_to="resume")

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .form import StudentForm
from .models import Student
import json

def get_author(request):
    template = loader.get_template("master.html")
    return HttpResponse(template.render())


def register(request):
    if request.method == "POST":
        form=StudentForm(request.POST, request.FILES)
        if form.is_valid():
            name = form["name"].data
            email = form["email"].data
            resume_file = request.FILES.get('resume')
            Student.objects.create(name=name, email=email, resume=resume_file)
            return HttpResponse("success")
        return HttpResponse(json.dumps(form.errors))
    form = StudentForm()
    context = {"form": form}
    return render(request, "register.html", context)



# def submitaction(request):
#     form = StudentForm(request.POST, request.FILES)
#     if form.is_valid():
#         name = form["name"].data
#         email = form["email"].data
#         resume_file = request.FILES.get('resume')
#         Student.objects.create(name = name, email = email, resume=resume_file)
#         return HttpResponse("success")
#     return HttpResponse(json.dumps(form.errors))

blog/templates/author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for author in authors %}
<h1> Hi {{ author.name }} </h1>
{% endfor %}
</body>
</html>

blog/templates/child.html
{% extends "master.html" %}

{% block user %}
<h2> we are inside child block</h2>
{% endblock %}

blog/templates/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> THIS IS MY FIRST PAGE</h1>
</body>
</html>

blog/templates/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" href="{% static "myfirst.css" %}">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> this is master file</h1>

{% block user %}
<h2> we are inside master block</h2>
<img src="{% static "pic.jpg" %}" width="300" height="300">
{% endblock %}

<p1> thanks </p1>
</body>
</html>

blog/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'blog:register' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
       {{ form.as_p }}
    </table>
    <input type = "submit" value = "Register">
</form>
</body>
</html>

blog/templates/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if p1 < 10  %}
<h1> THIS IS fake PAGE</h1>
{% else %}
<h1> THIS IS ORIGINAL PAGE</h1>
{% endif %}
</body>
</html>